server {
    listen 80;
    server_name _;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
        
        # 不设置 X-Frame-Options，允许 WebView 加载
        add_header X-Frame-Options "";
        
        # 允许跨域
        add_header Access-Control-Allow-Origin *;
    }
}